#!/usr/bin/env python3
"""
extract_data_inits.py - Generate a C header containing initial values
for arm9 .data static slots that the decompiled C code currently
zero-inits (which causes immediate NPE on the host port).

The script reads the user's own legally-owned ROM-derived arm9.bin and
emits a header with byte arrays + numeric constants ready to be
#included from pc/src/host_data_init.c.

USAGE:
    python extract_data_inits.py <arm9.bin> <output.h>

The header is written to a build-only directory (e.g.
pc/build/generated/) and is gitignored. ROM-derived bytes MUST NOT be
committed to source control - they are copyrighted.

The slot manifest below lists every (RAM address, byte size, C label)
tuple we want to lift out of arm9.bin. Add new entries as more decomp
work uncovers more uninitialized .data slots.
"""

import os
import sys
import struct

# arm9.bin is loaded at this RAM address by the NDS bootloader (matches
# header offset 0x28 in baserom.nds for Mario & Luigi PiT US v1.0).
ARM9_LOAD_BASE = 0x02004000


# Slot manifest: each entry is (ram_addr, size_bytes, c_label).
# - For pointer/scalar slots, size is 4 (or 2/1 for halfword/byte).
# - For blob slots (e.g. config arrays), size is the blob length.
#
# The generated header exposes:
#   * #define HOSTDATA_<LABEL>  <hex value>      (for size 1/2/4)
#   * static const u8 HOSTDATA_<LABEL>_BYTES[]   (always)
#
# Callers in host_data_init.c can pick whichever form fits.
SLOTS = [
    # game_init.c clGameMain factory slots (FUN_02005b70 family).
    (0x02005D28, 4,  "DAT_02005D28"),  # sGameState slot ptr (we override)
    (0x02005D2C, 4,  "DAT_02005D2C"),  # clGameMain alloc size = 0x58C
    (0x02005D30, 4,  "DAT_02005D30"),  # cfg-blob intra-struct offset = 0x57C
    (0x02005D34, 4,  "DAT_02005D34"),  # config blob ptr = 0x02048F44
    (0x02005D38, 4,  "DAT_02005D38"),  # display-mode flag ptr = 0x02059C8C
    (0x02005D68, 4,  "DAT_02005D68"),  # scene-jump fn ptr = 0x0202A56C

    # Default config blob (32 bytes at 0x02048F44, pointed to by
    # DAT_02005D34). FUN_02005b70 reads up to puVar2[6] / +0xC bytes -
    # 32 bytes is generous and matches the natural .data alignment.
    (0x02048F44, 32, "CONFIG_BLOB_02048F44"),
]


def emit_header(arm9_path: str, out_path: str) -> None:
    with open(arm9_path, "rb") as f:
        arm9 = f.read()

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    lines = []
    lines.append("/* Auto-generated by tools/scripts/extract_data_inits.py")
    lines.append(" * DO NOT EDIT, DO NOT COMMIT.")
    lines.append(" * Contents are derived from the user's own arm9.bin and")
    lines.append(" * therefore are copyrighted Nintendo machine data.")
    lines.append(" */")
    lines.append("#ifndef HOST_DATA_INIT_GENERATED_H")
    lines.append("#define HOST_DATA_INIT_GENERATED_H")
    lines.append("")
    lines.append(f"#define HOSTDATA_ARM9_LOAD_BASE 0x{ARM9_LOAD_BASE:08X}u")
    lines.append("")

    for ram_addr, size, label in SLOTS:
        off = ram_addr - ARM9_LOAD_BASE
        if off < 0 or off + size > len(arm9):
            raise SystemExit(
                f"slot {label} 0x{ram_addr:08X} (+{size}) out of arm9.bin "
                f"range (size {len(arm9)})")
        chunk = arm9[off:off + size]

        lines.append(f"/* {label}: ram=0x{ram_addr:08X} size={size} */")
        if size in (1, 2, 4):
            if size == 1:
                value = chunk[0]
            elif size == 2:
                (value,) = struct.unpack_from("<H", chunk, 0)
            else:
                (value,) = struct.unpack_from("<I", chunk, 0)
            lines.append(f"#define HOSTDATA_{label} 0x{value:0{size*2}X}u")

        byte_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(
            f"static const unsigned char HOSTDATA_{label}_BYTES[{size}] = "
            f"{{ {byte_str} }};")
        lines.append("")

    lines.append("#endif /* HOST_DATA_INIT_GENERATED_H */")
    lines.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"[extract_data_inits] wrote {out_path} "
          f"({len(SLOTS)} slots from {arm9_path})")


def main(argv):
    if len(argv) != 3:
        print(__doc__)
        return 2
    emit_header(argv[1], argv[2])
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
