#!/usr/bin/env python3
"""
gen_fnptr_table.py — generate pc/src/fnptr_table.c (gitignored).

Scans arm9/src/*.c for top-level function definitions whose names match
the pattern FUN_<8hex>. Emits a C source file that registers each one
with the host fnptr resolver at startup, mapping the NDS code address
into a callable host function pointer.

Usage:
    python tools/scripts/gen_fnptr_table.py <arm9_src_dir> <out_c>
"""
import os
import re
import sys

# Match a function definition line: returntype FUN_xxxxxxxx(... at column 0.
# Reject `extern` declarations and forward-decls (lines ending in `;`).
FUNC_DEF_RE = re.compile(r'^([A-Za-z_][\w\s\*]*?)\bFUN_([0-9a-fA-F]{8})\s*\(')


def scan(arm9_src_dir):
    addrs = {}
    for name in sorted(os.listdir(arm9_src_dir)):
        if not name.endswith('.c'):
            continue
        path = os.path.join(arm9_src_dir, name)
        try:
            with open(path, 'r', encoding='utf-8', errors='replace') as fh:
                lines = fh.readlines()
        except OSError:
            continue
        # First pass: find every FUN_<addr> that has a `static` forward
        # declaration anywhere in the file. C linkage is whole-file:
        # if the prototype says static, the definition (with or without
        # the keyword) inherits internal linkage.
        static_addrs = set()
        for line in lines:
            ls = line.lstrip()
            if not ls.startswith('static'):
                continue
            for m in re.finditer(r'\bFUN_([0-9a-fA-F]{8})\b', ls):
                static_addrs.add(m.group(1).lower())
        for line in lines:
            stripped = line.rstrip('\n').rstrip('\r')
            if not stripped:
                continue
            ls = stripped.lstrip()
            if ls.startswith('extern'):
                continue
            if ls.startswith('static'):
                continue
            if stripped.rstrip().endswith(';'):
                continue
            m = FUNC_DEF_RE.match(stripped)
            if not m:
                continue
            addr_hex = m.group(2).lower()
            if addr_hex in static_addrs:
                continue
            try:
                addr = int(addr_hex, 16)
            except ValueError:
                continue
            # ARM9 main code range
            if not (0x02000000 <= addr < 0x02400000):
                continue
            addrs.setdefault(addr_hex, name)
    return addrs


def emit(out_path, addrs):
    out = []
    out.append('/* AUTO-GENERATED by tools/scripts/gen_fnptr_table.py — do not edit. */\n')
    out.append('#include <stdint.h>\n')
    out.append('#include "sdk_symbol_aliases.h"\n')
    out.append('\n')
    out.append('extern void host_fnptr_register(uint32_t nds_addr, void *host_fn);\n')
    out.append('\n')
    # Forward decls — generic to avoid signature conflicts with the
    # alias-rewritten real implementations. The macros in
    # sdk_symbol_aliases.h rewrite FUN_<addr> tokens to the real symbol
    # name where one exists; for everything else we declare extern and
    # take the address.
    for addr_hex in sorted(addrs.keys()):
        out.append(f'extern void FUN_{addr_hex}();\n')
    out.append('\n')
    out.append('void host_fnptr_register_decompiled(void)\n')
    out.append('{\n')
    for addr_hex in sorted(addrs.keys()):
        out.append(f'    host_fnptr_register(0x{addr_hex}u, (void *)FUN_{addr_hex});\n')
    out.append('}\n')
    out.append(f'\n/* {len(addrs)} entries */\n')
    with open(out_path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.writelines(out)


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    arm9_src_dir, out_path = argv[1], argv[2]
    if not os.path.isdir(arm9_src_dir):
        print(f'error: {arm9_src_dir} is not a directory', file=sys.stderr)
        return 2
    addrs = scan(arm9_src_dir)
    os.makedirs(os.path.dirname(out_path) or '.', exist_ok=True)
    emit(out_path, addrs)
    print(f'wrote {out_path} ({len(addrs)} entries)')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
