#!/usr/bin/env python3
"""gen_dat_init_from_stubs.py - generate a C source that copies real
.data initial values from arm9.bin into every `DAT_<addr>` global
declared in pc/src/host_undefined_stubs.c.

The decompiled ARM9 C uses `DAT_<addr>` symbols as plain C globals, so
they end up in BSS at whatever virtual address the host linker picks -
NOT at NDS address 0x02000000+.  Mapping arm9.bin at 0x02000000 (see
nds_arm9_ram.c) only helps decomp paths that read through raw pointer
literals; it does nothing for `*&DAT_xxx` reads.

This script closes the gap: at host startup we walk a static table of
(symbol_address, &symbol, sizeof_symbol) tuples and memcpy the
ROM-extracted bytes from `extracted/arm9.bin` directly into each
host-side global.  No ROM bytes touch the source tree - the table is
just a list of addresses; the bytes live in the user's arm9.bin and
are loaded at runtime via nds_arm9_ram_base().

Inputs:
  $1 - path to pc/src/host_undefined_stubs.c
  $2 - path to pc/build/generated/dat_init_table.h (will be written)
  $3 - path to pc/build/generated/nds_dat_init_generated.c (will be written)

Both outputs are gitignored (build dir).  Re-runs on every CMake
configure step.

Skipped symbols:
  * DAT_<addr> with addr < 0x02004000  (BIOS / register space, not in arm9.bin)
  * DAT_<addr> with addr+4 > load_end   (past arm9.bin end)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ARM9_LOAD_BASE = 0x02004000     # arm9.bin file offset 0 maps here
ARM9_NDS_BASE  = 0x02000000     # the VirtualAlloc base on the host

# Pull addresses from any C declaration that mentions DAT_<addr>.
DECL_RE = re.compile(
    r"^\s*(?:extern\s+)?"
    r"(?P<ty>uint8_t|uint16_t|uint32_t|uint64_t|uintptr_t|"
    r"int8_t|int16_t|int32_t|int64_t|"
    r"u8|u16|u32|u64|s8|s16|s32|s64|"
    r"int|short|char|long|void\s*\*)\s+"
    r"DAT_(?P<addr>[0-9A-Fa-f]{8})\s*"
    r"(?:=[^;]*)?\s*;",
    re.MULTILINE,
)

TYPE_SIZE = {
    "uint8_t": 1, "int8_t": 1, "u8": 1, "s8": 1, "char": 1,
    "uint16_t": 2, "int16_t": 2, "u16": 2, "s16": 2, "short": 2,
    "uint32_t": 4, "int32_t": 4, "u32": 4, "s32": 4, "int": 4, "long": 4,
    "uint64_t": 8, "int64_t": 8, "u64": 8, "s64": 8,
    "void*": 8, "void *": 8,    # host pointer width
}


def parse_stubs(path: Path) -> list[tuple[int, str, int]]:
    """Return list of (addr, type_str, size_bytes) for every DAT_<addr> decl."""
    text = path.read_text(encoding="utf-8", errors="replace")
    out: dict[int, tuple[str, int]] = {}
    for m in DECL_RE.finditer(text):
        addr = int(m.group("addr"), 16)
        ty = re.sub(r"\s+", "", m.group("ty"))
        size = TYPE_SIZE.get(ty, 4)
        # host_undefined_stubs.c may declare the same DAT_xxx twice
        # (uint32_t plus an extern); keep the largest size.
        prev = out.get(addr)
        if prev is None or size > prev[1]:
            out[addr] = (ty, size)
    return [(a, t, s) for a, (t, s) in sorted(out.items())]


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    stubs_path = Path(sys.argv[1])
    out_header = Path(sys.argv[2])
    out_source = Path(sys.argv[3])
    out_header.parent.mkdir(parents=True, exist_ok=True)

    decls = parse_stubs(stubs_path)
    if not decls:
        print("[gen_dat_init] no DAT_<addr> decls found", file=sys.stderr)
        return 1

    # Header: extern declarations + the apply function.
    h = []
    h.append("/* AUTO-GENERATED by tools/scripts/gen_dat_init_from_stubs.py */")
    h.append("/* Do not edit; regenerated by every CMake configure step.   */")
    h.append("/* Do NOT commit - lives under build/.                       */")
    h.append("#ifndef NDS_DAT_INIT_TABLE_H")
    h.append("#define NDS_DAT_INIT_TABLE_H")
    h.append("#include <stdint.h>")
    h.append("#include <stddef.h>")
    h.append("")
    h.append(f"#define NDS_DAT_INIT_COUNT {len(decls)}")
    h.append("")
    h.append("typedef struct {")
    h.append("    uint32_t  nds_addr;   /* 0x02xxxxxx */")
    h.append("    void     *host_ptr;   /* &DAT_xxx in this process */")
    h.append("    uint32_t  size;       /* bytes to copy from arm9.bin */")
    h.append("    const char *name;")
    h.append("} nds_dat_init_entry_t;")
    h.append("")
    h.append("extern const nds_dat_init_entry_t nds_dat_init_table[NDS_DAT_INIT_COUNT];")
    h.append("")
    # extern decls so the table can take addresses
    for addr, ty, _sz in decls:
        sym = f"DAT_{addr:08x}"
        h.append(f"extern {ty} {sym};")
    h.append("")
    h.append("#endif")
    h.append("")
    out_header.write_text("\n".join(h), encoding="utf-8")

    # Source: the table itself + nds_apply_dat_inits().
    s = []
    s.append("/* AUTO-GENERATED by tools/scripts/gen_dat_init_from_stubs.py */")
    s.append("/* Regenerated every CMake configure; do NOT commit.          */")
    s.append('#include "dat_init_table.h"')
    s.append('#include "nds_platform.h"')
    s.append("#include <stdint.h>")
    s.append("#include <string.h>")
    s.append("")
    s.append("const nds_dat_init_entry_t nds_dat_init_table[NDS_DAT_INIT_COUNT] = {")
    for addr, ty, sz in decls:
        sym = f"DAT_{addr:08x}"
        s.append(
            f"    {{ 0x{addr:08x}u, (void*)&{sym}, {sz}u, \"{sym}\" }},"
        )
    s.append("};")
    s.append("")
    s.append("/* Walk the table and memcpy bytes from the VirtualAlloc'd")
    s.append(" * arm9.bin shadow at 0x02000000 into every host-side DAT_<addr>")
    s.append(" * global.  No-op if nds_arm9_ram_init() did not get the fixed")
    s.append(" * mapping (e.g. address space conflict). */")
    s.append("void nds_apply_dat_inits(void) {")
    s.append("    if (!nds_arm9_ram_is_mapped()) {")
    s.append("        nds_log(\"[dat-init] arm9 ram not mapped - skipping %d slots\\n\",")
    s.append("                NDS_DAT_INIT_COUNT);")
    s.append("        return;")
    s.append("    }")
    s.append(f"    const uint32_t arm9_base = 0x{ARM9_NDS_BASE:08x}u;")
    s.append(f"    const uint32_t arm9_top  = arm9_base + (4u * 1024u * 1024u);")
    s.append("    const uint8_t *ram = (const uint8_t *)nds_arm9_ram_base();")
    s.append("    int copied = 0, skipped = 0;")
    s.append("    for (int i = 0; i < NDS_DAT_INIT_COUNT; ++i) {")
    s.append("        const nds_dat_init_entry_t *e = &nds_dat_init_table[i];")
    s.append("        /* Only addresses inside the 4 MiB ARM9 main RAM window are")
    s.append("         * backed by our VirtualAlloc'd arm9.bin shadow.  IO-aliased")
    s.append("         * names like DAT_040000b0 / DAT_05000000 are register slots,")
    s.append("         * not RAM, and must be left as zero. */")
    s.append("        if (e->nds_addr < arm9_base || e->nds_addr + e->size > arm9_top) {")
    s.append("            skipped++; continue;")
    s.append("        }")
    s.append("        uint32_t off = e->nds_addr - arm9_base;")
    s.append("        memcpy(e->host_ptr, ram + off, e->size);")
    s.append("        copied++;")
    s.append("    }")
    s.append("    nds_log(\"[dat-init] copied %d/%d DAT_<addr> globals from arm9.bin"
             " (%d skipped: BIOS/IO range)\\n\", copied, NDS_DAT_INIT_COUNT, skipped);")
    s.append("}")
    s.append("")
    out_source.write_text("\n".join(s), encoding="utf-8")

    print(f"[gen_dat_init] wrote {len(decls)} entries -> {out_header}, {out_source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
